import { Router } from "express";

import { aiBrandMaterialRoutes } from "./ai-brand-material.routes.js";
import { aiHistoricalContentRoutes } from "./ai-historical-content.routes.js";
import { aiMetricInsightRoutes } from "./ai-metric-insight.routes.js";
import { aiScheduleRoutes } from "./ai-schedule.routes.js";
import { aiTeamAutomationRoutes } from "./ai-team-automation.routes.js";
import { auditRoutes } from "./audit.routes.js";
import { assetLibraryRoutes } from "./asset-library.routes.js";
import { authRoutes } from "./auth.routes.js";
import { carouselRoutes } from "./carousel.routes.js";
import { classScheduleRoutes } from "./class-schedule.routes.js";
import { contentApprovalRoutes } from "./content-approval.routes.js";
import { contentProductionRoutes } from "./content-production.routes.js";
import { copywritingRoutes } from "./copywriting.routes.js";
import { contentStatusRoutes } from "./content-status.routes.js";
import { contentIdeaRoutes } from "./content-idea.routes.js";
import { dashboardRoutes } from "./dashboard.routes.js";
import { discordOperationRoutes } from "./discord-operation.routes.js";
import { editorialCalendarRoutes } from "./editorial-calendar.routes.js";
import { emailCampaignRoutes } from "./email-campaign.routes.js";
import { externalIntegrationRoutes } from "./external-integration.routes.js";
import { launchRoutes } from "./launch.routes.js";
import { liveEventRoutes } from "./live-event.routes.js";
import { operationalEmailRoutes } from "./operational-email.routes.js";
import { operationalChecklistRoutes } from "./operational-checklist.routes.js";
import { operationalScheduleRoutes } from "./operational-schedule.routes.js";
import { platformSettingRoutes } from "./platform-setting.routes.js";
import { profileRoutes } from "./profile.routes.js";
import { publicationRoutes } from "./publication.routes.js";
import { productionChecklistRoutes } from "./production-checklist.routes.js";
import { reelRoutes } from "./reel.routes.js";
import { roleRoutes } from "./role.routes.js";
import { storySequenceRoutes } from "./story-sequence.routes.js";
import { strategyRoutes } from "./strategy.routes.js";
import { studentRoutes } from "./student.routes.js";
import { supportTicketRoutes } from "./support-ticket.routes.js";
import { trafficAudienceRoutes } from "./traffic-audience.routes.js";
import { trafficCampaignRoutes } from "./traffic-campaign.routes.js";
import { trafficConversionEventRoutes } from "./traffic-conversion-event.routes.js";
import { trafficCreativeRoutes } from "./traffic-creative.routes.js";
import { trafficPixelRoutes } from "./traffic-pixel.routes.js";
import { trafficReportRoutes } from "./traffic-report.routes.js";
import { trafficRoiRoutes } from "./traffic-roi.routes.js";
import { youtubeContentRoutes } from "./youtube-content.routes.js";
import { userRoutes } from "./user.routes.js";

export const apiRoutes = Router();

apiRoutes.get("/", (_request, response) => {
  response.status(200).json({
    service: "flow-jl-api",
    version: "v1",
    modules: ["ai-brand-materials", "ai-historical-contents", "ai-metric-insights", "ai-schedules", "ai-team-automations", "assets", "audits", "auth", "carousels", "class-schedules", "content-approvals", "content-ideas", "content-productions", "content-statuses", "copywritings", "dashboards", "discord-operations", "editorial-calendar", "emails", "external-publication", "launches", "live-events", "operational-checklists", "operational-emails", "operational-schedules", "platform-settings", "production-checklists", "profiles", "publications", "reels", "roles", "stories", "strategies", "students", "support-tickets", "traffic-audiences", "traffic-campaigns", "traffic-conversion-events", "traffic-creatives", "traffic-pixels", "traffic-reports", "traffic-roi", "users", "youtube-contents", "swagger"]
  });
});

apiRoutes.use("/ai-brand-materials", aiBrandMaterialRoutes);
apiRoutes.use("/ai-historical-contents", aiHistoricalContentRoutes);
apiRoutes.use("/ai-metric-insights", aiMetricInsightRoutes);
apiRoutes.use("/ai-schedules", aiScheduleRoutes);
apiRoutes.use("/ai-team-automations", aiTeamAutomationRoutes);
apiRoutes.use("/assets", assetLibraryRoutes);
apiRoutes.use("/audits", auditRoutes);
apiRoutes.use("/auth", authRoutes);
apiRoutes.use("/carousels", carouselRoutes);
apiRoutes.use("/class-schedules", classScheduleRoutes);
apiRoutes.use("/content-approvals", contentApprovalRoutes);
apiRoutes.use("/content-productions", contentProductionRoutes);
apiRoutes.use("/copywritings", copywritingRoutes);
apiRoutes.use("/content-ideas", contentIdeaRoutes);
apiRoutes.use("/content-statuses", contentStatusRoutes);
apiRoutes.use("/dashboards", dashboardRoutes);
apiRoutes.use("/discord-operations", discordOperationRoutes);
apiRoutes.use("/editorial-calendar", editorialCalendarRoutes);
apiRoutes.use("/emails", emailCampaignRoutes);
apiRoutes.use("/external-publication", externalIntegrationRoutes);
apiRoutes.use("/launches", launchRoutes);
apiRoutes.use("/live-events", liveEventRoutes);
apiRoutes.use("/operational-checklists", operationalChecklistRoutes);
apiRoutes.use("/operational-emails", operationalEmailRoutes);
apiRoutes.use("/operational-schedules", operationalScheduleRoutes);
apiRoutes.use("/platform-settings", platformSettingRoutes);
apiRoutes.use("/profiles", profileRoutes);
apiRoutes.use("/publications", publicationRoutes);
apiRoutes.use("/production-checklists", productionChecklistRoutes);
apiRoutes.use("/reels", reelRoutes);
apiRoutes.use("/roles", roleRoutes);
apiRoutes.use("/stories", storySequenceRoutes);
apiRoutes.use("/students", studentRoutes);
apiRoutes.use("/support-tickets", supportTicketRoutes);
apiRoutes.use("/traffic-audiences", trafficAudienceRoutes);
apiRoutes.use("/strategies", strategyRoutes);
apiRoutes.use("/traffic-campaigns", trafficCampaignRoutes);
apiRoutes.use("/traffic-conversion-events", trafficConversionEventRoutes);
apiRoutes.use("/traffic-creatives", trafficCreativeRoutes);
apiRoutes.use("/traffic-pixels", trafficPixelRoutes);
apiRoutes.use("/traffic-reports", trafficReportRoutes);
apiRoutes.use("/traffic-roi", trafficRoiRoutes);
apiRoutes.use("/youtube-contents", youtubeContentRoutes);
apiRoutes.use("/users", userRoutes);
